### ISSUE TITLE
Insufficient info in error messages

### ISSUE THREAD

**Issue by stepaunov** [microsoft/azuredatastudio-postgresql#161]
Please provide full info in error messages, e.g. line number, position, query text.

For example, run this query :
```
select a
from b_not_exists;
```

Result in Azure Data Studio:
Message:
```
Started executing query at Line 1
relation "b_not_exists" does not exist
Total execution time: 00:00:00.004
 ```

Result in psql:
```
ERROR:  relation "b_not_exists" does not exist
LINE 2: from b_not_exists;
             ^
```

**Comment by trevorsc** [comment]
Just bumping this topic - I'm looking for a good replacement for pgadmin and decided to give this extension a try.

This bug will make it hard to understand where errors occur in a complex script, since there's no line number in the message.

This following example is trivial, but I imagine I'll be running into this a lot as I learn both Postgres and Azure DS:

```
select *
from customer

SELECT d.datname as "Name",
       pg_catalog.pg_get_userbyid(d.datdba) as "Owner",
       pg_catalog.pg_encoding_to_char(d.encoding) as "Encoding",
       d.datcollate as "Collate",
       d.datctype as "Ctype",
       pg_catalog.array_to_string(d.datacl, E'\n') AS "Access privileges"
FROM pg_catalog.pg_database d
ORDER BY 1;
```

Error from the Azure DS extension:

```
8:23:37 PM Started executing query at Line 1
syntax error at or near "SELECT"
Total execution time: 00:00:00.003
```

Error from psql:

```
ERROR:  syntax error at or near "SELECT"
LINE 3: SELECT d.datname as "Name",
        ^
```

(Missed a semicolon, simple in this case. But the error message from Azure DS is vague and could be better - syntax error near which select? The first or the second?)

**Comment by DaeunYim** [comment]
Duplicate https://github.com/microsoft/azuredatastudio-postgresql/issues/283
